/* ----------------------------------------------------------------------------
 * iocpStubInit.c --
 *
 *	This file contains the initializers for the Iocpsock stub vectors.
 *
 * ----------------------------------------------------------------------------
 * RCS: @(#) $Id: iocpStubInit.c,v 1.9 2009/03/22 19:28:28 davygrvy Exp $
 * ----------------------------------------------------------------------------
 */

#include "iocpsockInt.h"

/*
 * WARNING: The contents of this file are automatically generated by the
 * $(ROOT)/tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the iocpsock.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

IocpIntStubs iocpIntStubs = {
    TCL_STUB_MAGIC,
    NULL,
    DecodeIpSockaddr, /* 0 */
    DecodeIrdaSockaddr, /* 1 */
    DecodeIpxSockaddr, /* 2 */
    InitSockets, /* 3 */
    IocpInitProtocolData, /* 4 */
    CreateSocketAddress, /* 5 */
    FreeSocketAddress, /* 6 */
    FindProtocolInfo, /* 7 */
    PostOverlappedAccept, /* 8 */
    PostOverlappedRecv, /* 9 */
    PostOverlappedQOS, /* 10 */
    IocpWinConvertWSAError, /* 11 */
    FreeBufferObj, /* 12 */
    GetBufferObj, /* 13 */
    NewSocketInfo, /* 14 */
    FreeSocketInfo, /* 15 */
    HasSockets, /* 16 */
    NULL, /* 17 */
    NULL, /* 18 */
    Iocp_IrdaDiscovery, /* 19 */
    Iocp_IrdaIasQuery, /* 20 */
    IocpLLCreate, /* 21 */
    IocpLLDestroy, /* 22 */
    IocpLLPushBack, /* 23 */
    IocpLLPushFront, /* 24 */
    IocpLLPop, /* 25 */
    IocpLLPopAll, /* 26 */
    IocpLLPopBack, /* 27 */
    IocpLLPopFront, /* 28 */
    IocpLLIsNotEmpty, /* 29 */
    IocpLLNodeDestroy, /* 30 */
    IocpLLGetCount, /* 31 */
    IocpSetRecvMode, /* 32 */
};

static IocpStubHooks iocpStubHooks = {
    &iocpIntStubs
};

IocpStubs iocpStubs = {
    TCL_STUB_MAGIC,
    &iocpStubHooks,
    Iocpsock_Init, /* 0 */
    Iocpsock_SafeInit, /* 1 */
    Tcl_WinErrId, /* 2 */
    Tcl_WinErrMsg, /* 3 */
    Tcl_WinError, /* 4 */
    Iocp_OpenTcpClient, /* 5 */
    Iocp_OpenTcpServer, /* 6 */
    Iocp_MakeTcpClientChannel, /* 7 */
};

/* !END!: Do not edit above this line. */
